/*
 * Copyright (c) 2019-2020, Intel Corporation. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef SOCFPGA_F2SDRAMMANAGER_H
#define SOCFPGA_F2SDRAMMANAGER_H

#include "socfpga_plat_def.h"

/* FPGA2SDRAM Register Map */

//#define SOCFPGA
#define SOCFPGA_F2SDRAMMGR_SIDEBANDMGR_FLAGINSTATUS0	0x14
#define SOCFPGA_F2SDRAMMGR_SIDEBANDMGR_FLAGOUTCLR0	0x54
#define SOCFPGA_F2SDRAMMGR_SIDEBANDMGR_FLAGOUTSET0	0x50

#if PLATFORM_MODEL == PLAT_SOCFPGA_STRATIX10
#define FLAGOUTCLR0_F2S_IDLEREQ			(BIT(0) | BIT(3) | BIT(6))
#define FLAGINTSTATUS0_F2S_IDLEACK		(BIT(1) | BIT(5) | BIT(9))
#define FLAGOUTCLR0_F2S_FORCE_DRAIN		(BIT(2) | BIT(5) | BIT(8))
#define FLAGOUTSET0_F2S_ENABLE			(BIT(1) | BIT(4) | BIT(7))
#define FLAGOUTSET0_F2S_FORCE_DRAIN		(BIT(2) | BIT(5) | BIT(8))
#define FLAGINSTATUS0_F2S_IDLE_STATUS		(BIT(3) | BIT(7) | BIT(11))

#elif PLATFORM_MODEL == PLAT_SOCFPGA_AGILEX
#define FLAGOUTCLR0_F2S_IDLEREQ			(BIT(0))
#define FLAGINTSTATUS0_F2S_IDLEACK		(BIT(1))
#define FLAGOUTSET0_F2S_ENABLE			(BIT(1))
#define FLAGOUTSET0_F2S_FORCE_DRAIN		(BIT(2))
#define FLAGINSTATUS0_F2S_IDLE_STATUS		(BIT(3))
#endif

#define SOCFPGA_F2SDRAMMGR(_reg)	(SOCFPGA_F2SDRAMMGR_REG_BASE \
						+ (SOCFPGA_F2SDRAMMGR_##_reg))

#endif /* SOCFPGA_F2SDRAMMGR_H */
